### ISSUE TITLE
FirefoxNightlyWayland does not start

### ISSUE THREAD

**Issue by rugk** [xhorak/firefox-devedition-flatpak#49] opened 2017-11-12 12:26 UTC
Since a few versions FirefoxNightlyWayland does not start. It used to start a few weeks or so ago, but now it does not anymore.

The FirefoxDeveloperEdition starts, e.g.

BTW: How can I start the flatpak manually from the CLI, so I can see possible CLI errors?

GNOME
Fedora 26

**Comment by anassahmed** [comment] 2017-11-12 14:27
Same here, I've this problem since the 1st of november. I've extracted the coredump from ABRT on Fedora 27 beta.

This is the output of `coredumpctl info`:
```bash
           PID: 15683 (firefox)
           UID: 1000 (anass)
           GID: 1000 (anass)
        Signal: 11 (SEGV)
     Timestamp: Sun 2017-11-12 16:19:46 EET (6min ago)
  Command Line: firefox
    Executable: /newroot/app/lib/firefox-58.0a1/firefox
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (anass)
       Boot ID: 5eb8e25538cb4b5b972e514c8e61d776
    Machine ID: fe5660cf957c4ac6bd8d3ab170ec772b
      Hostname: anass-galago
       Storage: /var/lib/systemd/coredump/core.firefox.1000.5eb8e25538cb4b5b972e514c8e61d776.15683.1510496386000000.lz4
       Message: Process 15683 (firefox) of user 1000 dumped core.
                
                Stack trace of thread 2:
                #0  0x0000003b0aa10f3f n/a (n/a)
                #1  0x0000003b0aa11060 n/a (n/a)
```

[firefox-wayland-coredump.zip](https://github.com/xhorak/firefox-devedition-flatpak/files/1464751/firefox-wayland-coredump.zip)

**Comment by anassahmed** [comment] 2017-11-12 14:34
I don't know if we should report this to the [upstream project](https://github.com/stransky/gecko-dev) or not.

It's maybe the source code fault, not the flatpak package, but I can't confirm right now because I don't have time to compile the source code itself outside of flatpak.

**Comment by rugk** [comment] 2017-11-12 19:19
> BTW: How can I start the flatpak manually from the CLI, so I can see possible CLI errors?

Any idea?

**Comment by anassahmed** [comment] 2017-11-12 19:23
@rugk It doesn't produce any errors (or output at all) when you run it from the command line, but you can try:
```bash
flatpak run org.mozilla.FirefoxNightlyWayland
```

This is why I got the core-dump, it's the only thing that contains useful information for developers/maintainers.

**Comment by xhorak** [comment] 2017-11-13 11:35
I can reproduce it. It seems to be some merging issue in github, @stransky will look at it.

Anyway, if you ever wish to Firefox in flatpak you need to install debuginfo first:
`flatpak install org.mozilla.FirefoxRepo org.mozilla.FirefoxNightlyWayland.Debug`
and execute by:
`flatpak run --devel --command=sh org.mozilla.FirefoxNightlyWayland`
that gets you into shell inside flatpak, then
`gdb firefox`
`run`
after crash, obtain backtrace by `bt` command.

**Comment by anassahmed** [comment] 2017-11-16 21:57
I think this issue has been fixed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1416186

Last update opened for me properly. Yet, the CSD patch didn't arrive with the Wayland version of the Nightly.

**Comment by rugk** [comment] 2017-11-16 22:16
As for CSD you may need to enable `browser.tabs.drawInTitlebar` and `widget.allow-client-side-decoration` in the settings. At least it works in Firefox 57 (in Fedora), but according to [the issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1283299#c98) it is only enabled in that Fedora built until now.

**Comment by anassahmed** [comment] 2017-11-16 22:27
> As for CSD you may need to enable browser.tabs.drawInTitlebar and widget.allow-client-side-decoration in the settings. At least it works in Firefox 57 (in Fedora), but according to the issue it is only enabled in that Fedora built until now.

The Wayland Nightly Flatpak doesn't have the CSD patch apparently, so the option `widget.allow-client-side-decoration` isn't available in `about:config`.

Hopefully, both my dreams (Wayland + CSD) come true in the next 58 release or at the most: 59 release. It will be a big celebration as I wait that day since GNOME 3.10 (first implementation of CSD in Nautilus).

**Comment by rugk** [comment] 2017-11-16 22:31
As for CSD you may need to enable `browser.tabs.drawInTitlebar` and `widget.allow-client-side-decoration` in the settings. At least it works in Firefox 57 (in Fedora), but according to [the issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1283299#c98) it is only enabled in that Fedora built until now.

**Comment by xhorak** [comment] 2018-01-30 14:36
Nightly now should have all necessary patches for CSD and also for Wayland. See https://firefox-flatpak.mojefedora.cz/#news for instruction how to enable CSD. 

Closing as this issue was already resolved.

**Closed by xhorak** 2018-01-30 14:36 UTC
