### ISSUE TITLE
Add usb devices access, to allow Firefox to log-in with U2F

### ISSUE THREAD

**Issue by andrevmatos** [xhorak/firefox-devedition-flatpak#87] opened 2018-08-18 21:09 UTC
Recently, Google fixed their sh*t, and it's now compatible with webauthn/u2f devices on Firefox too, just tested on Firefox 61 through system packages. It'd be nice to have these flatpaked versions to also be able to access the usb devices and support this usecase.

**Comment by rugk** [comment] 2018-10-20 14:11
Dupe of this is here: https://github.com/xhorak/firefox-devedition-flatpak/issues/95

**Comment by rugk** [comment] 2018-10-20 14:13
No, real first issue is: https://github.com/xhorak/firefox-devedition-flatpak/issues/51

**Comment by narwhalofages** [comment] 2019-01-04 04:54
Does anyone know if there is a 'bug bounty' program that the team has open for this repo? I need u2f support for several popular web services I use, and would happily contribute for the purposes of getting this actively looked at (and of course to support the development of the flatpak!)

**Comment by rugk** [comment] 2019-03-19 11:24
So I decided to tackle this issue, where it can (I think) be solved: In flatpak.

Here is a new issue:
https://github.com/flatpak/xdg-desktop-portal/issues/989

**Comment by erAck** [comment] 2020-03-27 20:10
Closing as duplicate of flatpak/flatpak#51

**Closed by erAck** 2020-03-27 20:10 UTC
