### ISSUE TITLE
Can't update DevEdition: Stream error in the  HTTP/2 framing layer

### ISSUE THREAD

**Issue by extrilldi** [xhorak/firefox-devedition-flatpak#43] opened 2017-09-20 21:08 UTC
Hello. Tried to update, and it simply won't

```
$ flatpak update org.mozilla.FirefoxDevEdition -v
Looking for updates...
XA: Updating dependent runtime runtime/org.gnome.Platform/x86_64/3.24
XA: Transaction: update gnome:runtime/org.gnome.Platform/x86_64/3.24[$old]
XA: Transaction: install/update gnome:runtime/org.gnome.Platform.Locale/x86_64/3.24[/en]
XA: Transaction: update org.mozilla.FirefoxRepo:app/org.mozilla.FirefoxDevEdition/x86_64/master[$old]
XA: Transaction: install/update org.mozilla.FirefoxRepo:runtime/org.mozilla.FirefoxDevEdition.Locale/x86_64/master[/en]
XA: Updating remote metadata for gnome
XA: Updating remote metadata for org.mozilla.FirefoxRepo
Updating: org.mozilla.FirefoxDevEdition/x86_64/master from org.mozilla.FirefoxRepo
[##################- ] Downloading files: 24/26 35.5 MB (1.1 MB/s)                 
Error: Failed to update org.mozilla.FirefoxDevEdition/x86_64/master: While pulling app/org.mozilla.FirefoxDevEdition/x86_64/master from remote org.mozilla.FirefoxRepo: [92] Stream error in the HTTP/2 framing layer
error: One or more operations failed
```

Probably a misconfigured server, or an issue with my system, not as much as a bug in the build.

I used the flatpakrepo method to install it originally.

System information:
`OS: Fedora 26`
`Flatpak 0.9.12`

**Comment by jurf** [comment] 2017-09-22 06:37
It’s a known problem with the host AFAIK, I use this to get the job done:

    sh -c "until flatpak update; do echo 'Trying again'; sleep 2; done"

**Comment by glaubersm** [comment] 2017-09-22 21:55
Every time I need to update the Wayland build on Arch is a nightmare.
Tried several times and I always get the same result:

> Error: Failed to update org.mozilla.FirefoxNightlyWayland/x86_64/master: While pulling app/org.mozilla.FirefoxNightlyWayland/x86_64/master from remote org.mozilla.FirefoxNightlyWayland-2-origin: Need more input
error: One or more operations failed

**Comment by xhorak** [comment] 2017-09-29 09:11
Sorry, we've run of space on the server again, so this could be related. It should be fine now.

**Comment by jurf** [comment] 2017-10-01 16:33
Still an issue.

**Comment by extrilldi** [comment] 2017-10-04 18:58
It seems to be working now, as it updated without major hiccups. A couple of days ago, into 57.0b3, and now into 57.0b6.
Thanks.
  

> run out of space

Perhaps a cron job to clean whatever is eating the disk space should be adjusted  to do it in shorter intervals, as @jurf still has the same issue. The problem could hit people differently in different timezones.

**Comment by jurf** [comment] 2017-10-05 19:20
@xhorak still an issue, can’t update anything:

```
❯ flatpak update
Looking for updates...
Aktualizovanie: org.mozilla.FirefoxNightly/x86_64/master z org.mozilla.FirefoxRepo
[###################=] Downloading files: 48/49 35,8 MB (526,2 kB/s)                 
Error: Failed to update org.mozilla.FirefoxNightly/x86_64/master: While pulling app/org.mozilla.FirefoxNightly/x86_64/master from remote org.mozilla.FirefoxRepo: [92] Stream error in the HTTP/2 framing layer
Aktualizovanie: org.mozilla.FirefoxNightlyCSD/x86_64/master z org.mozilla.FirefoxRepo
[####################] Downloading files: 19/20 32,8 MB (619,7 kB/s)                 
Error: Failed to update org.mozilla.FirefoxNightlyCSD/x86_64/master: While pulling app/org.mozilla.FirefoxNightlyCSD/x86_64/master from remote org.mozilla.FirefoxRepo: [92] Stream error in the HTTP/2 framing layer
Aktualizovanie: org.mozilla.FirefoxNightlyWayland/x86_64/master z org.mozilla.FirefoxRepo
[####################] Downloading metadata: 29/(estimating) 24,7 MB (632,9 kB/s) 
Error: Failed to update org.mozilla.FirefoxNightlyWayland/x86_64/master: While pulling app/org.mozilla.FirefoxNightlyWayland/x86_64/master from remote org.mozilla.FirefoxRepo: [92] Stream error in the HTTP/2 framing layer
chyba: One or more operations failed
```

I doubt it’s geography though, I live in Slovakia.

**Comment by jurf** [comment] 2017-10-13 17:20
IMHO this is a timeout-related issue, since when connected to a fast internet connection (1–2MB/s) Firefox updates normally, but with my home network (700KB/s) it fails most of the time.

Also when it almost always fails on the one before the last chunk, which is significantly bigger than the others. This may not mean anything, maybe it’s just because it’s at the end.

**Comment by Camille019** [comment] 2017-10-27 17:19
I am also affected by this issue. The update fails all the time with an Internet connection of 600 kB/s. It works well with a faster connection (2.5 MB/s).

```
>>> flatpak update
Looking for updates...
Updating: org.mozilla.FirefoxNightlyWayland/x86_64/master from org.mozilla.FirefoxRepo
[###################-] Downloading files: 40/41 31,5 MB (606,4 kB/s)            
Error: Failed to update org.mozilla.FirefoxNightlyWayland/x86_64/master: While pulling app/org.mozilla.FirefoxNightlyWayland/x86_64/master from remote org.mozilla.FirefoxRepo: [92] Stream error in the HTTP/2 framing layer
error: One or more operations failed
```

**Comment by jurf** [comment] 2017-11-06 17:54
Hate to continue bugging but even after installing flatpak `0.10.0` updating is nearly [impossible](https://pastebin.com/1hccGDds) on a 600–700KB/s connection.

**Comment by msehnout** [comment] 2017-11-10 13:04
Same for me, regardless the flatpak version.
```
Looking for updates...
Updating: org.mozilla.FirefoxNightlyCSD/x86_64/master from org.mozilla.FirefoxNightlyCSD-origin
[##################- ] Downloading files: 35/38 34.0 MB (830.4 kB/s)               
Error: Failed to update org.mozilla.FirefoxNightlyCSD/x86_64/master: While pulling app/org.mozilla.FirefoxNightlyCSD/x86_64/master from remote org.mozilla.FirefoxNightlyCSD-origin: [92] Stream error in the HTTP/2 framing layer
error: One or more operations failed

```

**Comment by zkanda** [comment] 2017-11-15 04:41
I'm getting the same issue.

**Comment by Ramblurr** [comment] 2017-11-15 07:32
Also here.. is this flatpak repo still maintained?

**Comment by xhorak** [comment] 2017-11-21 09:21
Yes, it is, we currently don't have fix for the buggy hosting :(.

**Comment by xhorak** [comment] 2017-11-21 09:24
Duplicate of #1

**Closed by xhorak** 2017-11-21 09:24 UTC

**Comment by jurf** [comment] 2017-11-21 15:25
@xhorak, I’m not sure if this is the same as #1, it’s even possible it’s a flatpak issue (see above for the reference bug).
