### ISSUE TITLE
Can't install Firefox developer edition

### ISSUE THREAD

**Issue by GuillaumeAmat** [xhorak/firefox-devedition-flatpak#1] opened 2017-01-09 07:49 UTC
I always get that output:

```
$ flatpak install --from https://firefox-flatpak.mojefedora.cz/firefox-devedition.flatpakref
Installing: org.mozilla.FirefoxDevEdition/x86_64/master
Updating: org.gnome.Platform/x86_64/3.20 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.20 from gnome
No updates.
Installing: org.mozilla.FirefoxDevEdition/x86_64/master from org.mozilla.FirefoxDevEdition-4-origin

Receiving objects: 99% (1291/1293) 266,2 kB/s 64,2 MB                                                                                                         
error: While pulling app/org.mozilla.FirefoxDevEdition/x86_64/master from remote org.mozilla.FirefoxDevEdition-4-origin: Need more input
```

Thanks for the flatpak « port » anyway, it's greatly appreciated :)

**Comment by xhorak** [comment] 2017-01-09 08:19
Thanks for the report. What distro are you using? What flatpak version do you have installed?

**Comment by GuillaumeAmat** [comment] 2017-01-09 08:22
How could I forget that...
I'm on Fedora 25, with flatpak (and flatpak-libs) 0.8.0.

**Comment by GuillaumeAmat** [comment] 2017-01-11 09:26
@xhorak Have you got any clue?

**Comment by xhorak** [comment] 2017-01-11 11:37
Sorry, no clue so far, however you can try to install flatpak bundle from here: [https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxDevEdition.flatpak](https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxDevEdition.flatpak) to see if that works. To install downloaded bundle use `flatpak install -v org.mozilla.FirefoxDevEdition.flatpak`
It's basically packaged repo in one file. You still need to have gnome platform installed (which you probably already have).

**Comment by alexlarsson** [comment] 2017-01-11 16:04
error: While pulling app/org.mozilla.FirefoxDevEdition/x86_64/master from remote org.mozilla.FirefoxDevEdition-4-origin: Need more input

Thius seems to come from:
```
./glib/gio/gzlibdecompressor.c:			     _("Need more input"));
./glib/gio/gzlibcompressor.c:			     _("Need more input"));
```

So, some issue uncompressing a file?

@cgwalters this seems to be from ostree pull. Any idea?

**Comment by GuillaumeAmat** [comment] 2017-01-12 07:54
@xhorak Thank you for the tip! It did it well :)

**Comment by xhorak** [comment] 2017-01-13 07:59
@GuillaumeAmat Please keep mind that `flatpak update org.mozilla.FirefoxDevEdition` won't work for you when you install bundle instead of application repository.

**Comment by alexlarsson** [comment] 2017-01-13 10:04
@xhorak If you specify --repo-url=URL and  --gpg-keys=FILE when  you build the bundle then updating after installing the bundle should work.

**Comment by xhorak** [comment] 2017-01-17 13:23
@alexlarsson okay, good to know. Will add to the build scripts.

**Comment by bmillemathias** [comment] 2017-02-17 07:58
I still experience the same issue 75% of the time I do a `flatpak update`

**Comment by nicber** [comment] 2017-02-17 22:18
If I wget the full bundle from your server it complains about the server closing the connection suddenly. It restarts the download from where it left off and eventually completes it.

It is possible that flatpak doesn't try to reconnect and, therefore, feeds incomplete data to the decompressor?

**Comment by xhorak** [comment] 2017-02-20 14:21
@bmillemathias Could you please attach output of `flatpak update -v --ostree-verbose` of the failure (shortened reasonable)? Thanks.

**Comment by srakitnican** [comment] 2017-02-20 14:58
@xhorak Here is mine, whole log. This is second time I tried to update without success, that's why there is less output.
[flatpak-firefox-Nightly.txt](https://github.com/xhorak/firefox-devedition-flatpak/files/787799/flatpak-firefox-Nightly.txt)

**Comment by xhorak** [comment] 2017-02-20 15:22
@srakitnican Thanks, tail of the verbose output:
```
XA: fetch of 949a2ca7b638c938f048bc3e89335a084dbe4e77d78ca4c43dccc5167e268040.file complete
XA: write of 949a2ca7b638c938f048bc3e89335a084dbe4e77d78ca4c43dccc5167e268040.file complete
XA: fetch of fc6fc61a6c9a6b4452c6c054a8c905e1da9c659948246a58928218edc7dac05e.file complete
XA: write of fc6fc61a6c9a6b4452c6c054a8c905e1da9c659948246a58928218edc7dac05e.file complete
XA: fetch of b6b794471b0f9062b54feea9a290b0b95f6d46d172282cea79440e9f7b546293.file complete
XA: write of b6b794471b0f9062b54feea9a290b0b95f6d46d172282cea79440e9f7b546293.file complete
XA: fetch of 70a50b6e63db70fdda2df753da61af662875270a14464e58c83b9b2384bf82a2.file complete
XA: write of 70a50b6e63db70fdda2df753da61af662875270a14464e58c83b9b2384bf82a2.file complete
XA: fetch of 6320a4231ddef8f9dc41cd1753b075863648f8183150f65f16bdb57f8a3257c4.file complete
Error: Failed to update org.mozilla.FirefoxNightly/x86_64/master: While pulling app/org.mozilla.FirefoxNightly/x86_64/master from remote org.mozilla.FirefoxNightly-origin: Need more input
```

Log from server:
```
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:35 -0500] "GET /repo/objects/1e/12f8765bb004c61989cf1056a683a9d21652b6f631604f252700b1f5eac19f.filez HTTP/1.1" 200 63696 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:35 -0500] "GET /repo/objects/9b/9f77ca3cb90981e74131113fa69091afa51e9a2f5c0f9079719ab88226f623.filez HTTP/1.1" 200 116 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:35 -0500] "GET /repo/objects/dd/70947c53aae6ab9b2726b8978cf0f66a80d0a181198ef2afecc157abeab09b.filez HTTP/1.1" 200 1563 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:35 -0500] "GET /repo/objects/fc/6fc61a6c9a6b4452c6c054a8c905e1da9c659948246a58928218edc7dac05e.filez HTTP/1.1" 200 3699214 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:33 -0500] "GET /repo/objects/63/20a4231ddef8f9dc41cd1753b075863648f8183150f65f16bdb57f8a3257c4.filez HTTP/1.1" 200 27083186 "-" "ostree libsoup/2.52.2"
- - - [20/Feb/2017:09:52:38 -0500] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.2.15 (Red Hat) (internal dummy connection)"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:54 -0500] "GET /repo/config HTTP/1.1" 200 38 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:54 -0500] "GET /repo/summary.sig HTTP/1.1" 200 313 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:54 -0500] "GET /repo/summary HTTP/1.1" 200 4549 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:55 -0500] "GET /repo/objects/72/5890a950fa98724a4e6a1527f7cbb4ef302fa3c2af52239ed225c0c93cf12c.commitmeta HTTP/1.1" 200 313 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:55 -0500] "GET /repo/objects/72/5890a950fa98724a4e6a1527f7cbb4ef302fa3c2af52239ed225c0c93cf12c.commit HTTP/1.1" 200 214 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:55 -0500] "GET /repo/objects/46/95e5a0eb3f0dd558eec50d363bbaeeed3a4b3935fe1dc66f8c3f041e829906.dirtree HTTP/1.1" 200 117 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:55 -0500] "GET /repo/objects/05/cb5bda0fb4f08dc783379cab69b7e98041a97a9db1a6a1b46dc8b1f8dd538c.filez HTTP/1.1" 200 85 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:55 -0500] "GET /repo/objects/72/5890a950fa98724a4e6a1527f7cbb4ef302fa3c2af52239ed225c0c93cf12c.commitmeta HTTP/1.1" 200 313 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:52:55 -0500] "GET /repo/objects/10/ab5ce36fc55009df4c5a3fc2bcbc802fe3e73558de7de6d9acc00e5ea00ea1.dirtree HTTP/1.1" 200 5471 "-" "ostree libsoup/2.52.2"
[IP ADDRESS], [IP ADDRESS2] - - [20/Feb/2017:09:53:49 -0500] "GET /repo/summary.sig HTTP/1.1" 200 313 "-" "ostree libsoup/2.52.2"
```

Failed file is: https://firefox-flatpak.mojefedora.cz/repo/objects/63/20a4231ddef8f9dc41cd1753b075863648f8183150f65f16bdb57f8a3257c4.filez


@cgwalters, @allexlarson: Seems that server is fine (but it serve the file as [text/plain]) , could you make some of these?

**Comment by xhorak** [comment] 2017-02-20 15:38
Server is now sending application/octet-stream mime types for all repo files (.filez, .dirtree, .commit, .dirmeta). Please check if that helped.

**Comment by srakitnican** [comment] 2017-02-20 15:49
This did not help for me.

```
XA: Using cached summary for remote org.mozilla.FirefoxNightly-origin
XA: starting fetch of 6c058262c95c00e976b9af426645a6464b858560de5cb5be5d4180b15e9250c5.commit (detached)
XA: starting fetch of 6320a4231ddef8f9dc41cd1753b075863648f8183150f65f16bdb57f8a3257c4.file
XA: fetch of 6c058262c95c00e976b9af426645a6464b858560de5cb5be5d4180b15e9250c5.commit (detached) complete
XA: fetch of 6320a4231ddef8f9dc41cd1753b075863648f8183150f65f16bdb57f8a3257c4.file complete
Error: Failed to update org.mozilla.FirefoxNightly/x86_64/master: While pulling app/org.mozilla.FirefoxNightly/x86_64/master from remote org.mozilla.FirefoxNightly-origin: Need more input
```

After this try it updated fine. As always it needs couple of tries (4-5 maybe).

**Comment by marsjaninzmarsa** [comment] 2017-04-24 06:23
Almost always I need to retry 1-2 times, irritating (LMDE 2, Flatpak 0.8.5).

**Comment by glaubersm** [comment] 2017-06-23 14:27
Wayland build update frequently fails on Arch, flatpak 0.9.6
https://bugs.kde.org/show_bug.cgi?id=381417

**Comment by kwill** [comment] 2017-10-14 22:53
I'm getting the same issue. I don't seem to benefit from previous downloads, unless I'm misreading something?

    ~> flatpak remote-add --from org.mozilla.FirefoxRepo https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo
    ~> flatpak install org.mozilla.FirefoxRepo org.mozilla.FirefoxNightlyCSD
    Installing: org.mozilla.FirefoxNightlyCSD/x86_64/master from org.mozilla.FirefoxRepo
    [####################] Downloading files: 177/178 50.1 MB (834.9 kB/s)             
    error: While pulling app/org.mozilla.FirefoxNightlyCSD/x86_64/master from remote org.mozilla.FirefoxRepo: Need more input
    ~> flatpak install org.mozilla.FirefoxRepo org.mozilla.FirefoxNightlyCSD
    Installing: org.mozilla.FirefoxNightlyCSD/x86_64/master from org.mozilla.FirefoxRepo
    [####################] Downloading files: 177/178 47.5 MB (932.3 kB/s)             
    error: While pulling app/org.mozilla.FirefoxNightlyCSD/x86_64/master from remote org.mozilla.FirefoxRepo: Need more input
    ~> flatpak install org.mozilla.FirefoxRepo org.mozilla.FirefoxNightlyCSD
    Installing: org.mozilla.FirefoxNightlyCSD/x86_64/master from org.mozilla.FirefoxRepo
    [####################] Downloading files: 177/178 47.5 MB (914.3 kB/s)             
    error: While pulling app/org.mozilla.FirefoxNightlyCSD/x86_64/master from remote org.mozilla.FirefoxRepo: Need more input

    ~> flatpak --version
    Flatpak 0.9.98.2

(running on PureOS, a Debian derivative)

**Comment by deikatsuo** [comment] 2018-01-16 03:16
Error: While pulling app/org.mozilla.FirefoxNightlyCSD/x86_64/master from remote org.mozilla.FirefoxNightlyCSD-origin: Need more input
Archlinux - Flatpak 0.10.2.1

**Comment by mthw0** [comment] 2018-01-25 16:20
This happens also to me but only when I use slow internet connection ~5Mbit/s but everything works fine on ~100Mbit/s. Like there is some time limit to download all the files. Arch - Flatpak latest

**Comment by xhorak** [comment] 2018-01-30 14:55
We've moved to different hosting. Let's see if it helped.

**Comment by jurf** [comment] 2018-02-02 21:14
@xhorak just came to see what happened because suddenly it just worked and has worked since! Thanks!

**Comment by bmillemathias** [comment] 2018-02-03 07:41
I can confirm it works fine now

**Comment by jurf** [comment] 2018-02-04 20:18
Eh, now I’m getting this:
```
Looking for updates...
Aktualizovanie [Updating]: org.mozilla.FirefoxNightly/x86_64/master z org.mozilla.FirefoxRepo
[-                   ] Downloading metadata: 1/(estimating) 1,8 kB (1,8 kB/s)
Error: Failed to update org.mozilla.FirefoxNightly/x86_64/master: While pulling app/org.mozilla.FirefoxNightly/x86_64/master from remote org.mozilla.FirefoxRepo: Writing content object: Potrebných viac vstupov [More inputs needed]
chyba [error]: One or more operations failed
```

**Comment by glaubersm** [comment] 2018-02-05 02:33
update fails on Arch Linux too.

**Comment by Wrexthor** [comment] 2018-02-08 11:53
On Arch
Flatpak 0.10.3
Getting
$ flatpak install org.mozilla.FirefoxRepo org.mozilla.FirefoxDevEdition
Installing: org.mozilla.FirefoxDevEdition/x86_64/master from org.mozilla.FirefoxRepo
[                    ] Downloading metadata: 2/(estimating) 427,2 kB
error: While pulling app/org.mozilla.FirefoxDevEdition/x86_64/master from remote org.mozilla.FirefoxRepo: Writing content object: Need more input

**Comment by bmillemathias** [comment] 2018-02-08 12:10
It worked fine few days ago but now I got the same error than above for 3 days

**Comment by erAck** [comment] 2020-03-09 12:44
Outdated.

**Closed by erAck** 2020-03-09 12:44 UTC
