### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Wetrain** [xhorak/firefox-devedition-flatpak#127] opened 2019-06-20 13:06 UTC
I noticed 8 open pull request and the Gnome runtime is outdated, is development still active?

**Comment by ramcq** [comment] 2019-06-20 14:43
I suspect the momentum will have been significantly reduced now that the Fedora alternate-universe Flatpak build system has produced a Firefox flatpak. https://registry.fedoraproject.org/repo/firefox/tags/

**Comment by Wetrain** [comment] 2019-06-20 14:46
@ramcq that URL shows nothing for me, or is that a remote that i can add and install firefox from?

**Comment by ramcq** [comment] 2019-06-20 14:50
Oh, that's the wrong link. That's the OCI registry for Fedora, which their RPM -> Flatpak woodchipper outputs to. I don't actually know how to add the remote in Flatpak though.

**Comment by Wetrain** [comment] 2019-06-20 14:51
Oh nice that's cool, would be good to consume something more stable, all my fonts are funted on this build :(

**Comment by MicrosoftTakeover** [comment] 2019-07-03 01:07
`flatpak remote-add fedora oci+https://registry.fedoraproject.org`

**Comment by rugk** [comment] 2019-07-06 13:09
> all my fonts are funted on this build :(

Maybe it's https://github.com/xhorak/firefox-devedition-flatpak/issues/106/https://github.com/xhorak/firefox-devedition-flatpak/issues/126#issuecomment-495101543

**Comment by ndarilek** [comment] 2019-09-30 22:38
This repository's website states:

We're committed to updating this repository until we state otherwise on this website.

So if it's dead and/or unsupported, it might be wise to update that.

For my part, I was using Firefox nightly builds from this repo. I then started hitting issues other web developers couldn't reproduce. After a bit of digging, I discovered that the nightly build hadn't been updated since late August.

So now I'm on the Fedora stable flatpak, but before investigating this issue tracker, I checked the website to see that verbiage still in place. Maybe it was naive of me to think that would be taken down if maintenance ever lapsed, but I took it at face value. :)

**Comment by oleid** [comment] 2019-11-10 21:29
> I suspect the momentum will have been significantly reduced now that the Fedora alternate-universe Flatpak build system has produced a Firefox flatpak. https://registry.fedoraproject.org/repo/firefox/tags/

Tried that, doesn't support h264 videos :/

**Comment by erAck** [comment] 2020-03-09 12:23
Reviving to bring DevEdition and Nightly in shape.

**Closed by erAck** 2020-03-09 12:23 UTC
