### ISSUE TITLE
Wayland version seriously broken on HiDPI

### ISSUE THREAD

**Issue by daniellandau** [xhorak/firefox-devedition-flatpak#8] opened 2017-02-16 07:42 UTC
This is what it looks like for me:

![kuvakaappaus - 2017-02-16 09-38-52](https://cloud.githubusercontent.com/assets/1044056/23011839/c3224d42-f42b-11e6-8451-8cc3484ea6f2.png)

The system top bar looks to be less than half of the width of the content. Also there's a message about a crashed tab and nothing in the UI is responding to clicks.

It still makes me happy to see at least something of Firefox running on Wayland.

**Comment by wjt** [comment] 2017-02-16 08:12
For me, the UI responds to clicks as if the widgets had been rendered in the correct place. Try clicking on the 'e' of "New Tab" – this focuses the address bar for me.

**Comment by xhorak** [comment] 2017-02-16 08:28
Thanks for the report, I guess @stransky will be interested.

**Comment by daniellandau** [comment] 2017-02-16 08:28
Oh yeah, it's the same on my machine. Although for me it's slightly below the text, but the cursor changes so you can figure out when it's at the correct place.

**Comment by fabrixx** [comment] 2017-03-03 22:51
Same situation for me on Arch Linux I have an UHD monitor:
![schermata del 2017-03-02 23-26-10](https://cloud.githubusercontent.com/assets/1190942/23571948/4cf2fc78-006c-11e7-9008-1e2fb5370f0c.png)

**Comment by pkgw** [comment] 2017-04-11 15:16
Another small data point. I have a machine with one HiDPI display and one regular-DPI display. If I drag the window from my HiDPI display to the regular-DPI display, the window size suddenly becomes matched to the title bar, but most text in the chrome is rendered twice as big as it should be. Text within pages is fine.

**Comment by kubrickfr** [comment] 2017-06-07 10:48
I get slightly better results launching firefox with GDK_DPI_SCALE=0.5 GDK_SCALE=1 but the UI is still double what it should be and it's not usable...

**Comment by kubrickfr** [comment] 2017-06-30 06:46
I think @stansky has officially picked up the task https://bugzilla.mozilla.org/show_bug.cgi?id=1345666

**Comment by wvengen** [comment] 2017-10-24 09:29
As the upstream bug still mentions _UNCONFIRMED_, I'll add a me-too. Hope this will get fixed!

**Comment by wvengen** [comment] 2017-11-13 13:06
Sorry if this is off-topic, but maybe it helps to report the following.
When I build https://github.com/stransky/gecko-dev/commit/899b80142ae8dcd48f41eb7ee0699b986b184ac9 from source (with `cairo-gtk3-wayland` toolkit), running it on a laptop with retina display (2x) and external monitor (1x), I observe the following behaviour:
* On 2x display, browser is upscaled, mouse location is off, popups show on wrong place. [ss2-2x](https://user-images.githubusercontent.com/503804/32727039-617d1f8e-c87b-11e7-935c-36ff6f981cf6.png)
* On 1x display, browser looks fine but fonts are large, mouse is fine, popups on wrong place. [ss2-1x](https://user-images.githubusercontent.com/503804/32727109-9ae121da-c87b-11e7-8398-39b8c353b38c.png)
* On 1x display, if window size becomes roughly twice the width or more, acts similar to 2x display. (E.g. if I half-maximize the window to the right half of the screen, the window decorations are shown there but the window contents fills the whole screen.)

Then, without really knowing what I'm doing, making the following change based on [this hint](https://bugzilla.mozilla.org/show_bug.cgi?id=1345666#c6):
```diff
diff --git a/widget/gtk/WindowSurfaceWayland.cpp b/widget/gtk/WindowSurfaceWayland.cpp
index 0b727cadea1b..9b0595fe6ea9 100644
--- a/widget/gtk/WindowSurfaceWayland.cpp
+++ b/widget/gtk/WindowSurfaceWayland.cpp
@@ -397,6 +397,7 @@ void
 WindowBackBuffer::Attach(wl_surface* aSurface)
 {
   wl_surface_attach(aSurface, mWaylandBuffer, 0, 0);
+  wl_surface_set_buffer_scale(aSurface, 2);
   wl_surface_commit(aSurface);
   wl_display_flush(mWaylandDisplay->GetDisplay());
   mAttached = true;
```
Running it on a laptop with retina display (2x) and external monitor (1x), I observe the following behaviour:
* On 2x display, browser looks fine, mouse pointer ok. Popups show on the wrong position. [scr 2x](https://user-images.githubusercontent.com/503804/32726266-a8a1fd6a-c878-11e7-9933-8f9af9adba67.png)
* On 1x display, browser and chrome take half size, mouse doesn't respond to correct location. Popups show on wrong position. [ss-1x](https://user-images.githubusercontent.com/503804/32726735-531db2ce-c87a-11e7-9a89-ef3702da0499.png)
* On 1x display, if window size becomes roughly twice the width or more, acts similar to 2x display.

**Comment by xhorak** [comment] 2017-11-20 08:21
Okay, some HiDPi support is now available in FirefoxNightlyWayland flatpak. Please give some feedback if you find any. I've also added support for normal dpi + hidpi monitor, so on recent gnome shell dragging between two monitors should work. 

What does not work properly is placing menus, tooltips and popups on normaldpi + hidpi displays, I'm working on that now.

**Comment by wvengen** [comment] 2017-11-20 15:41
I can confirm that it works on dpi + hidpi monitor combination (except popup placement as mentioned). Thanks!

**Comment by kubrickfr** [comment] 2017-11-20 16:17
This is a major improvement indeed

**Comment by pkgw** [comment] 2017-11-20 16:49
OMG, it works now! Thank you! This is a very valuable improvement in my day-to-day experience.

**Comment by xhorak** [comment] 2018-01-30 15:04
Wayland does not allow apps to get absolute position on the display, so saving and restoring position will never work under Wayland. Sorry, this is given by design. About popups, we're solving this issue in upstream bug https://bugzilla.mozilla.org/show_bug.cgi?id=1423598 

Currently since merge of FirefoxNightly and FirefoxWayland, we still need to finish [some hdi patches](https://bugzilla.mozilla.org/show_bug.cgi?id=1431337), so ATM things could be broken in FirefoxNightly.

**Comment by wvengen** [comment] 2018-03-15 09:25
I'm curious what's the status of this now, any progress on popup placement? Is help needed somewhere?

**Comment by wvengen** [comment] 2018-06-18 09:28
It looks like the [upstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1423598) was unblocked by [this GTK change](https://gitlab.gnome.org/GNOME/gtk/issues/997), so it's now possible that this gets fixed!

**Comment by erAck** [comment] 2020-04-06 15:36
This issue is outdated, upstream closed.

**Closed by erAck** 2020-04-06 15:36 UTC
