### ISSUE TITLE
KeePassXC-browser native messaging does not work with flatpak

### ISSUE THREAD

**Issue by oidualc** [xhorak/firefox-devedition-flatpak#92] opened 2018-08-24 13:37 UTC
### Subject of the issue
KeePassXC-Browser is unable to connect to KeePassXC, likely a problem with Native Messaging.
Probably relevant, the needed file `org.keepassxc.keepassxc_browser.json` is available in `~/.mozilla/native-messaging-hosts`, but not in `~/.var/app/org.mozilla.FirefoxNightly/.mozilla`. In fact the directory `native-messaging-hosts` is missing.

### Environment
* Arch Linux
* Firefox Nightly (flatpak)
* KeePassXC (flatpak, from dl.flathub.org) 

### Steps to reproduce
Assuming the availability of a working instance of KeePassXC, install the KeePassXC-Browser addon and try to connect.

### Expected behaviour
After having verified that on Firefox Nightly (non-flatpak) the extension works correctly, try to connect using Firefox Nightly (flatpak) and expect it working the same way.

### Actual behaviour
On Firefox Nightly (non-flatpak) the extension works as intended, on Firefox Nigthly (flatpak) the error message is "Timeout or not connected to KeePassXC".

**Comment by wvengen** [comment] 2018-09-10 09:03
You may be able to expose `native-messaging-hosts` e.g. by hardlinking the file to the `~/.var/...` path:

    ln ~/.mozilla/native-messaging-hosts ~/.var/app/org.mozilla.FirefoxNightly/.mozilla/native-messaging-hosts

Or perhaps use the `--persist` option to `flatpak run` to expose this file.

Perhaps the cleanest way would be to be able to pass some kind of `--socket=keepassxc` option to `flatpak run`, and let flatpak understand that option to expose the socket. I'd try my luck with the other options first.

**Comment by oidualc** [comment] 2018-09-10 20:31
Hi @wvengen, unfortunately I cannot hardlink native-messaging-hosts because it's actually a directory, not a file. The closest thing I can think is:
```
mkdir ~/.var/app/org.mozilla.FirefoxNightly/.mozilla/native-messaging-hosts
ln ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json ~/.var/app/org.mozilla.FirefoxNightly/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
```
but even like this it doesn't work.

With regard to the `--persist` and `--socket=keepassxc` options I don't know enough about flatpak to understand what I could try.

**Comment by rugk** [comment] 2019-02-01 20:45
@oidualc Can we maybe change the title of this issue to something like "Native messaging does not work with flatpak", which is more specific than the current one?

**Comment by rugk** [comment] 2019-04-13 15:39
BTW a workaround has been provided in [this issue](https://github.com/keepassxreboot/keepassxc-browser/issues/297#issuecomment-429235866) ([or here](https://github.com/flathub/org.keepassxc.KeePassXC/issues/29#issuecomment-477675488)) that works if KeePassXC is also installed as a flatpak.

**Comment by kaymio** [comment] 2019-04-15 09:14
Thank you @rugk for your effort to solve this issue. 

With the wrapper script my native FF doesn't start KeePassXC in parallel, as intended. 

The flatpaked version of FF (this repo) still doesn't connect  to the flatpaked KeePassXC.

**Comment by rugk** [comment] 2019-04-15 10:41
Okay, hmm. Note I [have also been advised that DBUS could be used to spawn another process](https://unix.stackexchange.com/a/422438/146739), but AFAIK this is a thing that would have to be baked in, into this browser flatpak. (@xhorak, are you listening?)

@kaymio If you want to try it, you can create the following wrapper script as a workaround somewhere accessible to the Firefox flatpak (**and** keepassxc too, AFAIK, so in the worst case use `/opt` or maybe better your home dir?):
```sh
#!/bin/sh
flatpak-spawn --host keepassxc-proxy "$@"
```

I've based this loosely [on my other scripts here](https://github.com/rugk/atom-flatpak-wrapper/#atom-flatpak-wrapper).

Then `flatpak override this.app.ID --talk-name=org.freedesktop.Flatpak` (**Attention:** this allows this flatpak to start any commands on the host!) and then point keepassxc-browser to start this script instead of `keepassxc-proxy`. (I guess that is what you need 

This should allow Firefox to spawn a keepassxc-proxy on the host, so if keepassxc runs on the host, it works.

So now, you may want both as flatpaks. So [we also need to do step 4 here](https://github.com/flathub/org.keepassxc.KeePassXC/issues/13#issuecomment-372030281), which may end up in a script like this:
```sh
#!/bin/sh
flatpak-spawn --host exec /usr/bin/flatpak run --command=keepassxc-proxy --branch=master --arch=x86_64 org.keepassxc.KeePassXC "$@"
```

I am just not sure whether the whole thing with unix sockets and so on still works. In any case, take these as ideas, I guess it won't work exactly like this and there may still be bugs.

**Comment by kaymio** [comment] 2019-04-16 11:32
Unfortunately my skill level is not high enough to meddle that deeply with the system. Especially if it goes that deep:

> (Attention: this allows this flatpak to start any commands on the host!)

Nonetheless, thx! 

PS: There was some movement during the flatpak update today. Although it finished with an error.
Error: Message recipient disconnected from message bus without replying.
Also the build still relies on Gnome 3.24 which is deprecated as of 11th January. Don't know whether I should file a bug report.

**Comment by rugk** [comment] 2019-04-16 15:56
> Don't know whether I should file a bug report.

Unless it is fixed in the next second, yes. :smile: (also noticed that issue already)

**Comment by Ramblurr** [comment] 2019-12-13 13:26
@rugk your solution works for a flatpaked-firefox and a host-keepassxc, but it allows firefox to run arbitrary commands on the host, which severely reduces the benefit of running FF in a flatpak. :/ any idea how to restrict it further?

**Comment by rugk** [comment] 2019-12-13 13:56
Well… unfortunately I do not have any better idea. Because you need to grant Firefox host execution permissions or it just does not work :thinking:

**Comment by rugk** [comment] 2019-12-13 13:58
Okay maybe another idea I am not quite sure whether it works: AFAIK KeePassXC also supports some kind of "reverse connection", where KeePassXC actually spawns the proxy. This way KeePassXC could possibly spawn it _inside_ of the Firefox flatopak. (via `flatpak enter`)
But whether that works is another question. :thinking:

**Comment by rugk** [comment] 2020-05-05 20:29
FYI, for everyone following: I have found a working around involving some manual steps you need to do though for KeePassXC<->Firefox communication, if Firefox is flatpaked/sandboxed (works if KeePassXC is sandboxed or not). [Read the full write-up/tutorial here.](https://discourse.flathub.org/t/how-to-run-firefox-and-keepassxc-in-a-flatpak-and-get-the-keepassxc-browser-add-on-to-work/437?u=rugk)

**Comment by rugk** [comment] 2020-05-05 20:29
FYI, for everyone following: I have found a working around involving some manual steps you need to do though for KeePassXC<->Firefox communication, if Firefox is flatpaked/sandboxed (works if KeePassXC is sandboxed or not). [Read the full write-up/tutorial here.](https://discourse.flathub.org/t/how-to-run-firefox-and-keepassxc-in-a-flatpak-and-get-the-keepassxc-browser-add-on-to-work/437?u=rugk)

**Comment by erAck** [comment] 2020-06-24 11:43
This can not be soved in flatpackaging. There's upstream issue https://bugzilla.mozilla.org/show_bug.cgi?id=1621763 for native messaging in flatpak.
Use rugk's workaround.

**Closed by erAck** 2020-06-24 11:43 UTC
