### ISSUE TITLE
Font rendering doesn't work in Nightly

### ISSUE THREAD

**Issue by jkonecny12** [xhorak/firefox-devedition-flatpak#36] opened 2017-07-28 06:36 UTC
The GitHub missing all the text. Wayland version is working correctly for some reason. This is happening only for Firefox nightly in flatpak.

![screenshot from 2017-07-28 08-32-27](https://user-images.githubusercontent.com/1643889/28705387-d1bda8c4-736f-11e7-9dff-3df5288fdcb4.png)

**Comment by jkonecny12** [comment] 2017-07-28 06:38
Console output:
```
(firefox:2): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
1501223837091   addons.webextension.jid1-MnnxcxisBPnSXQ-eff@jetpack     WARN    Loading extension 'jid1-MnnxcxisBPnSXQ-eff@jetpack': Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
1501223837201   addons.webextension.jid1-MnnxcxisBPnSXQ-eff@jetpack     WARN    Please specify whether you want browser_style or not in your browser_action options.

(/app/lib/firefox-56.0a1/firefox:68): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
console.error:
  Message: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebProgress.removeProgressListener]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://browser/content/tabbrowser.xml :: _beginRemoveTab :: line 3001"  data: no]
  Stack:
    _beginRemoveTab@chrome://browser/content/tabbrowser.xml:3001:15
TSTWH_initTabbrowserMethods/b._beginRemoveTab@chrome://treestyletab/content/windowHelper.js:518:59
removeTab@chrome://browser/content/tabbrowser.xml:2848:18
ssi_restoreWindow@resource:///modules/sessionstore/SessionStore.jsm:3277:11
ssi_restoreWindows@resource:///modules/sessionstore/SessionStore.jsm:3526:5
initializeWindow@resource:///modules/sessionstore/SessionStore.jsm:1157:11
onBeforeBrowserWindowShown/<@resource:///modules/sessionstore/SessionStore.jsm:1306:9
promise callback*onBeforeBrowserWindowShown@resource:///modules/sessionstore/SessionStore.jsm:1291:5
ssi_observe@resource:///modules/sessionstore/SessionStore.jsm:758:9
onLoad@chrome://browser/content/browser.js:1358:5
onload@chrome://browser/content/browser.xul:1:1


(/app/lib/firefox-56.0a1/firefox:115): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
```

**Comment by garrett** [comment] 2017-07-29 15:53
This seems to be unique to Firefox Nightly in Flatpak.

I've tested the following other Nightly builds and they all display fonts properly on GitHub:
- Nightly Wayland Flatpak
- Nightly Developer Edition Flatpak
- Nightly tar.bz2 from Firefox

This is not unique to GitHub, as I have encountered other sites (notably OpenWRT/LEDE Bootstrap-based theme) which have exhibited this same behavior.

I had this happen a the day prior to this issue was filed.

---

A sub-optimal temporary workaround is to disable custom fonts in Firefox's prefs for the time being, until this is fixed. This means all custom fonts will not work, which breaks sites (especially those that depend on icon fonts, such as FontAwesome, which is included in Bootstrap).

**Comment by garrett** [comment] 2017-08-07 08:54
After playing around a bit in the inspector, I noticed that it's not remote fonts, but it does affect certain fonts.

For example: Open Sans gets rendered invisibly, even if it's just pulled from my own computer (and not specified as a remote web font).

Did anything change in the build with regard to fonts or font sandboxing? (A lot of fonts I know I have on my system don't seem to show up when I try to override font settings for websites.) Or did something like Pango, Cairo, or Skia change in Nightly and the Flatpak builds didn't adjust for it, causing rendering issues for some fonts?

The default sandbox for Flatpak according to https://github.com/flatpak/flatpak/wiki/Sandbox pertaining to fonts is "host fonts are bind mounted to `/run/host/fonts`". Perhaps Firefox doesn't know to look there?

Whatever is happening, it seems specific to the nightly Flatpak build of Firefox, not the dev or wayland builds (nor upstream nightly Firefox). I do also see the other Flatpaks of Firefox seem to be older builds, so that could be why they're not affected (yet?).

**Comment by garrett** [comment] 2017-08-07 08:58
So far, broken fonts here include:

- Roboto
- Droid Sans
- Helvetica
- Open Sans
...and I'm sure there's more.

And, again: This is when they're actually NOT served from the server, but should be coming from the local machine.

These are all pretty common fonts to use in font stacks, so a lot of sites are broken as a result of this bug.

**Comment by garrett** [comment] 2017-08-07 09:33
http://www.cssfontstack.com/ is an excellent demo of the problem as a bunch of the page simply doesn't render, and many of the font titles are also invisible.

---

You can see the fonts Firefox would have access to in `/run/host` by using the following URIs in Firefox's location bar:
- `file:///run/host/fonts/` — seems to be an export of `/usr/share/fonts`
- `file:///run/host/user-fonts/` —  seems to be an export of `$HOME/.local/share/fonts`

Other local font paths are not supported, including `$HOME/.fonts/`

**Comment by garrett** [comment] 2017-08-09 09:04
Any progress on this?

I've tried to see if it's related to DRI or the version of the runtime used (doesn't seem so)... I rebuilt Firefox Nightly in Flatpaks here in the background the past few days and I can't figure it out from my end.

It's a super-annoying issue, as it feels like half the sites on the 'Net don't work.

**Comment by garrett** [comment] 2017-08-10 07:32
## Quick report

...or How I spent a decent chunk of my evenings (mainly doing other things while waiting on the computer):

So I checked tons of settings in Firefox, and didn't find anything obvious that would make fonts work again.

I dug around and built Firefox several times (so slow to build!) with different sandbox flags and different runtimes and couldn't find anything responsible.

I even went as far as to make a way to build the upstream Nightly as a Flatpak (https://github.com/xhorak/firefox-devedition-flatpak/pull/41 or https://github.com/garrett/firefox-devedition-flatpak/tree/nightly-upstream) to check.

## The results

I still don't know why certain fonts are missing. But I do know that upstream Firefox Nightly running directly on the system doesn't have this problem. And thanks to adding the ability to take upstream Nightly and Flatpakize it, I know that running upstream Nightly in a Flatpak (with different versions of the runtimes even) still reproduces this issue. 

So it seems it's not related to _building_ in Flatpak, at least.

What the issue does seem to be is some minor difference(s) between the native system and what's in our Flatpak runtimes that recent Firefox nightlies happen to hit.

## Wild hunches

Yesterday evening, I decided to look through all the recent commits around the timeframe where things broke. And I found some freetype changes. You can see all the freetype related changes @:
https://hg.mozilla.org/mozilla-central/log?rev=freetype

It's probably related to one (or more) of the comments (or related commits that don't mention freetype? like possibly related to cairo, pango, and/or skia?) from 2017-07-27. (Seems like it could be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1383767)

Is Firefox dynamically linking to the system Freetype? And is our runtime different enough where fonts sometimes fail? Or is it possibly related to hardware acceleration that doesn't make its way through Flatpak? Just a bunch of wild speculation, but it's the best I have at the moment.

(I'm not a developer on this, only was a happy user of the Flatpak until lots of fonts stopped working on websites who did some digging around.)

**Comment by hungrymonkey** [comment] 2017-08-15 23:42
I actually have FirefoxNightlyWayland installed and I am having problem with fonts too.

**Comment by garrett** [comment] 2017-08-17 10:22
@hungrymonkey: To me (see comments above), it looks like an upstream change that doesn't play well in Flatpak. When Nightly was a problem and NightlyWayland wasn't, the Wayland build was simply a little out of date.

Now, this all being said — has anyone tried the Nightly Flatpak in X? Perhaps it's something to do with patches (most likely the ones I linked above) in Flatpak in Wayland? Not sure, but it would probably be interesting to know.

**Comment by alxlg** [comment] 2017-08-20 14:14
@garrett 
> has anyone tried the Nightly Flatpak in X?

I'm on KDE Plasma X session and Firefox Nightly via Flatpak doesn't display any font. Instead Firefox Nightly provided directly by Mozilla works well.

-----

Maybe this issue should be renamed "Font rendering doesn't work in Nightly" (no need to specify Flatpak since it's obvious because we are in this repo, otherwise it would be reported to Mozilla's bug tracker).

**Comment by jkonecny12** [comment] 2017-08-22 13:26
Renamed, thanks for suggestion @alxlg

**Comment by marsjaninzmarsa** [comment] 2017-08-23 18:36
Just blind guess, but may it be related to [Freetype recently bumped](https://bugzilla.mozilla.org/show_bug.cgi?id=1364714) in Firefox to 2.8 while still being 2.7.1 in [Flatpak runtime](http://flatpak.org/runtimes.html)? I had font issues **only if** there was variated (italics/bold) version used and they was successfully fixable by simple `font-style: normal !important` or so in Inspector.

**Comment by garrett** [comment] 2017-08-25 08:51
I'm on my phone at the moment, but a quick search shows that Fedora 26 uses freetype 2.7.1, and the official Firefox Nightly tarball works there just fine. The same exact tarball packaged as a flatpak (see my comments above) does not work, however. I don't think it's the version of the freetype library, but something related to that patch I pointed out, which landed at the same time fonts broke in Nightly in a Flatpak. 

It's possible for some fonts that variants could trigger the bug, but I have seen text in normal weights and without italics still break too.

What we do know is that it's not all fonts, it's not necessarily remote fonts, it's probably not the freetype library, and it's not with how Firefox is compiled for Flatpak.

What we do know is that it's a showstopping bug, highly annoying, happens with the official Firefox Nightly in Flatpak, and is in both X and Wayland.

It's _probably_ that recent font patchset. Someone would have to test it though, with that patched out on a recent build or an older build without that patch but with the patch applied.

Once we know if it is indeed that patch, it would either need to be fixed or the patch would need to be reverted upstream.

We should probably notify upstream Mozilla in that issue on Bugzilla too. 😉

**Comment by glaubersm** [comment] 2017-08-28 18:53
I installed both Nightly and Nightly Wayland today on Arch, I get this same result in KDE website using both builds.

![font bug](https://user-images.githubusercontent.com/15967631/29788431-edf29318-8c08-11e7-8bde-5cbaec7c7249.png)

**Comment by xhorak** [comment] 2017-09-04 13:25
After a while, we've (@alex) managed to debug that, it is a Mozilla sandbox related. The sandbox forbid access to the /run/host/fonts/... where fonts from system live. The workaround which I found to work so far is to set security.sandbox.content.level in about:config to 2. Note that you ease Mozilla sandboxing by this.
More info there: https://wiki.mozilla.org/Security/Sandbox

**Comment by garrett** [comment] 2017-09-07 09:49
@xhorak: Great to hear you've found the culprit.

Any leads on fixing it by exposing the fonts a directory Firefox expects or by patching the sandbox to allow that directory? (Hopefully the fix would go upstream, even?)

It's odd that previous builds worked and they suddenly stopped working, but I guess the font changes around the time there was a problem triggered it?

---

If I'm understanding it right, changing the sandbox level in Firefox  on Linux  (https://wiki.mozilla.org/Security/Sandbox#Linux) as suggested in your workaround basically allows for complete filesystem reading (within the Flatpak sandbox), basically disabling these protections:

> - Read access to most of the filesystem
>   - Excludes themes/GTK configuration, fonts, shared data and libraries

Which, obviously, isn't great, but I guess that's already limited by Flatpak anyway? (It's still good to abide by Firefox's sandbox limitations, even in Flatpak, just to be a bit safer.)

In this case, it exposes some typical font dirs, but not the "correct" ones (according to Firefox)?

**Comment by garrett** [comment] 2017-09-07 09:55
@xhorak: Might this be a better workaround? Add `/run/host/fonts/` to the `security.sandbox.content.read_path_whitelist` preference? (I haven't tested this.) It certainly isn't easier than changing a number though. :wink:

**Comment by nical** [comment] 2017-09-11 12:53
Related bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1390390

**Comment by oguzhanogreden** [comment] 2017-09-12 11:09
@garrett whitelisting `/run/host/fonts/` did not work for me on Debian 9. I guess this is not all surprising given that the directory `/run/host/` does not exist.

I have no idea how to follow up. Let me know if I can provide any information.

**Comment by xhorak** [comment] 2017-09-12 11:50
@oguzhanogreden what version of flatpak Debian 9 provides?
@alexlarsson Since what version we export /run/host/?

**Comment by oguzhanogreden** [comment] 2017-09-12 12:11
@xhorak, [version 0.8.5](https://packages.debian.org/stretch/flatpak-builder) currently.

**Comment by xhorak** [comment] 2017-09-13 14:30
@oguzhanogreden Hm, are you sure?  The /run/host is available only in flatpak runtime, to check that, use:
`flatpak -d  --command="bash" run org.mozilla.FirefoxNightly`
`ls /run/host`

**Comment by xhorak** [comment] 2017-09-13 14:30
@garrett Setting `security.sandbox.content.read_path_whitelist` for some reason does not work for me.

**Comment by xhorak** [comment] 2017-09-14 09:17
Added patch from from upstream:
https://bugzilla.mozilla.org/show_bug.cgi?id=1396733
into  a0c07e1aba76c20b9a5f604e6253607b3c050b5f should fix this.

**Comment by garrett** [comment] 2017-09-14 12:35
@xhorak, @alex: thanks!

**Comment by xhorak** [comment] 2017-09-18 08:30
Should be fine now, closing. Please reopen if you still have the problem.

**Closed by xhorak** 2017-09-18 08:30 UTC

**Comment by jkonecny12** [comment] 2017-09-18 08:44
@xhorak @alex: thanks a lot!
