### ISSUE TITLE
Uploading files outside of `Downloads` doesn't work [implement portal to the filesystem]

### ISSUE THREAD

**Issue by garrett** [xhorak/firefox-devedition-flatpak#33] opened 2017-07-24 09:34 UTC
How to reproduce:

1. Visit a page where you want to upload something ([Google Drive](https://drive.google.com), a nextcloud instance, [waifu2x](http://waifu2x.udp.jp/), GitHub issues, etc.)
2. Either click on an upload button to get a file selection dialog _or_ drag and drop files (if it's supported by the webapp).
3. You can't select files outside of the `Downloads` folder and drag and dropping files does not work.

I'm sure this is due to sandboxing.

The non-sandbox-breaking fix is to use portals for file uploading.

**Comment by xhorak** [comment] 2017-07-24 09:46
I guess it's in Nightly or Nightly Wayland, isn't it?

**Comment by kubrickfr** [comment] 2017-07-24 09:49
That's a great security **feature**, I do that on purpose with firejail instead of flatpack.

**Comment by garrett** [comment] 2017-07-24 12:31
Oh, this is in plain Nightly. Sorry. I should've specified.

**Comment by xhorak** [comment] 2017-07-24 12:33
The nightly does not allow the access to the home directory, so as @kubrickfr mentioned, it is actually desired behaviour.

**Comment by garrett** [comment] 2017-07-24 12:34
It's not a security "feature" though. It's a big problem. There needs to be a way to upload user-specified files.

**Comment by garrett** [comment] 2017-07-24 12:34
(This would be done with portals, of course.)

**Comment by garrett** [comment] 2017-07-24 12:35
Breaking an extremely basic feature of a web browser is not a "desired" feature.

**Comment by garrett** [comment] 2017-07-24 12:36
This is the portal that would need to be used: http://flatpak.org/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.impl.portal.FileChooser

**Comment by xhorak** [comment] 2017-07-24 12:36
To override it temporarily use:
flatpak run --filesystem=home:rw org.mozilla.FirefoxNightly
Yes, you're right, we need portals for this. So I leave it open.

**Comment by garrett** [comment] 2017-07-24 12:40
Of course, that existing portal is just for manual selection.

It's not for drag-and-drop. I don't know the answer there. I suppose there would have to be a special portal with a confirmation step that lists the files & directories about to be accessed? (I'm pretty sure more work would need to be done in Flatpak & Portals for D&D.)

**Comment by thebitstick** [comment] 2018-10-15 02:49
Any progress on this issue???

**Comment by mat8913** [comment] 2018-10-17 19:14
This is done now, isn't it?

https://bugzilla.mozilla.org/show_bug.cgi?id=1490186

**Comment by rugk** [comment] 2018-10-20 14:17
I can confirm at least the open dialog looks like the one in the flatpak-demo application.

**Comment by xhorak** [comment] 2018-11-08 09:56
This should be indeed fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1490186 Please reopen if you still see the issue in Nightly Flatpak.

**Closed by xhorak** 2018-11-08 09:56 UTC
